{{-- Form Template generated by FormGenerator --}}

{{ Form::errors($errors) }}

@if (isset($entity))
{{ Form::model($entity, ['route' => ['admin.newscats.update', $entity->id], 'files' => true, 'method' => 'PUT']) }}
@else
{{ Form::open(['url' => 'admin/newscats']) }}
@endif
        {{ Form::smartText('title', trans('app.title')) }}
        {{ Form::smartImageFile('image', trans('app.image')) }}
        
    {{ Form::actions() }}
{{ Form::close() }}