{{-- Form Template generated by SmartFormGenerator --}}

{{ Form::errors($errors) }}

@if (isset($entity))
{{ Form::model($entity, ['route' => ['admin.news.update', $entity->id], 'method' => 'PUT']) }}
@else
{{ Form::open(['url' => 'admin/news']) }}
@endif
        {{ Form::smartText('title', 'Title') }}
        {{ Form::smartTextarea('intro', 'Intro') }}
        {{ Form::smartTextarea('text', 'Text') }}
        {{ Form::smartCheckbox('published', 'Published') }}
        {{ Form::smartCheckbox('internal', 'Internal') }}
        {{ Form::smartCheckbox('allow_comments', 'Allow_comments') }}
        {{ Form::smartSelectForeign('newscat_id', 'Newscat_id', $entity) }}
        
    {{ Form::actions() }}
{{ Form::close() }}