{{-- Form Template generated by FormGenerator --}}

{{ Form::errors($errors) }}

@if (isset($model))
{{ Form::model($model, ['route' => ['admin.<?php echo($modulename) ?>.update', $model->id], 'method' => 'PUT']) }}
@else
{{ Form::open(['url' => 'admin/<?php echo($modulename) ?>']) }}
@endif
    <?php foreach ($fields as $field) { ?>
    <?php echo($field) ?>
    <?php } ?>
    
    {{ Form::actions() }}
{{ Form::close() }}