{{-- Form Template generated by FormGenerator --}}

{{ Form::errors($errors) }}

@if (isset($model))
{{ Form::model($model, ['route' => ['admin.partners.update', $model->id], 'method' => 'PUT']) }}
@else
{{ Form::open(['url' => 'admin/partners']) }}
@endif
    {{ Form::smartText('title', 'Title') }}
    {{ Form::smartTextarea('text', 'Text') }}
    {{ Form::smartUrl('url', 'URL', 'blub') }}
    {{ Form::smartNumeric('type', 'Type', 0) }}
    {{ Form::smartNumeric('position', 'Position', 0) }}
    {{ Form::smartImageFile('image', 'Image') }}
        
    {{ Form::actions() }}
{{ Form::close() }}